name: unsplash_gallery
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.0

flutter_native_splash:
  color: '#fcfcfc'
  image: 'lib/assets/images/app_logo.png'


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/images/app_logo.png'

flutter:


  uses-material-design: true


  assets:
    - lib/assets/images/app_logo.png

  # fonts:

